import SwiftUI

/// Dynamic Type-aware type roles used by shared components.
enum AISkinTypography {
    static let toastTitle = Font.system(.title3, weight: .semibold)
    static let processingTitle = Font.system(.subheadline, weight: .semibold)
    static let processingPercentage = Font.system(.title2, weight: .regular)
    static let screenTitle = Font.system(size: 22, weight: .semibold)
    static let featureTitle = Font.system(size: 17, weight: .semibold)
    static let sectionTitle = Font.system(.headline, design: .rounded, weight: .bold)
    static let cardTitle = Font.system(.headline, design: .rounded, weight: .semibold)
    static let body = Font.system(.body, design: .rounded)
    static let bodyEmphasized = Font.system(.body, design: .rounded, weight: .semibold)
    static let callout = Font.system(.callout, design: .rounded)
    static let caption = Font.system(.caption, design: .rounded)
    static let aiDisclosure = Font.system(.footnote, design: .rounded)
    static let button = Font.system(.body, design: .rounded, weight: .semibold)
    static let compactButton = Font.system(size: 14, weight: .semibold)
    static let heroMetric = Font.system(size: 28, weight: .bold, design: .rounded)
    static let captureGuideIcon = Font.system(size: 68, weight: .ultraLight)
    static let iconCaption = Font.system(size: 12, weight: .semibold)
    static let iconChevron = Font.system(size: 14, weight: .semibold)
    static let iconSmall = Font.system(size: 16, weight: .semibold)
    static let iconButton = Font.system(size: 17, weight: .semibold)
    static let iconControl = Font.system(size: 18, weight: .semibold)
    static let iconMedium = Font.system(size: 20, weight: .semibold)
    static let iconTitle = Font.system(size: 24, weight: .medium)
    static let iconLarge = Font.system(size: 36, weight: .medium)
    static let iconState = Font.system(size: 32, weight: .medium)
    static let iconUpload = Font.system(size: 30, weight: .semibold)

    static let compactCaption = Font.system(size: 11)
    static let cabinetEmptyTitle = Font.system(size: 30, weight: .medium)
    static let routineTitle = Font.system(size: 17, weight: .medium)
    static let routineCheck = Font.system(size: 18, weight: .regular)
    static let homeHeading = Font.system(size: 18, weight: .semibold)
    static let reportTab = Font.system(size: 12)
    static let reportTabSelected = Font.system(size: 12, weight: .semibold)
    static let categoryTab = Font.system(.callout, design: .rounded)
    static let categoryTabSelected = Font.system(.callout, design: .rounded, weight: .semibold)
    static let productTitle = Font.system(.callout, design: .rounded, weight: .semibold)
    static let featureIcon = Font.system(size: 24, weight: .regular)
    static let tabLabel = Font.system(size: 10)

    static let featureSubtitle = Font.system(size: 13)
    static let routineSubtitle = Font.system(size: 13)
    static let segmentedLabel = Font.system(size: 15, weight: .medium)

    static let reportBody = Font.system(.subheadline, design: .rounded)
}
